### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by bidhya** [USEPA/StreamCat#2]
I noticed some of the files from StreamCat database are missing on the ftp site. Can you please confirm if this was an oversight or if the files are missing for some reason.

ftp://newftp.epa.gov/EPADataCommons/ORD/NHDPlusLandscapeAttributes/StreamCat/HydroRegions/

NLCD2011_Region14.csv
NLCD2011_Region15.csv

**Comment by mhweber** [comment]
Thanks, @bidhya - this was an oversight on our part and those files have been added to ftp://newftp.epa.gov/EPADataCommons/ORD/NHDPlusLandscapeAttributes/StreamCat/HydroRegions/

**Comment by bidhya** [comment]
Can you please check the two files again. Indeed I was able to download these two files. But the columns for 2011 files are named 2006. It should have been in the format xxx2011xxx like other files. So I think there is still some problems with the new files.

**Comment by mhweber** [comment]
@bidhya - we had simply re-used a lookup table for field names based on NLCD 2006, and now have it corrected to use 'NLCD 2011' in the field names for the NLCD 2011 tables.  The updated files are up now on the ftp site.
