### ISSUE TITLE
AgDrain

### ISSUE THREAD

**Issue by debboutr** [USEPA/StreamCat#21]
- [x] Allocation and Accumulation
- [x] FinalTables
- [x] States
- [x] ZIPs
- [x] metadata

I believe this metric has already been run and put into StreamCat, the only thing that needs to be checked is that the original raster and lookup table are correct. 

@mhweber , the raster that was run to complete what we have in StreamCat is "AgDrain_stlvl_FINAL.tif", Pennino has it listed in his table as `AgDrain.tif` but he says that he was given it by you. Could you just confirm in a comment below that this is correct and that Pennino just need to change the name listed for this raster in his control table?

I will likely also need info as to how the "AgDrain_stlvl_FINAL.tif" was made for the metadata, if you have any info that would help.

**Comment by mhweber** [comment]
@debboutr , AgDrain_stlvl_FINAL.tif is the correct raster - it was created by Jay Christensen and they made a couple updates to that raster.  I will pass along an email with details on this raster.

**Comment by debboutr** [comment]
[Drainage2107product_methodsdocumentation.docx](https://github.com/USEPA/StreamCat/files/5038648/Drainage2107product_methodsdocumentation.docx)
[Exploring the extent of artificial agricultural drainage_2019posterv2.pdf](https://github.com/USEPA/StreamCat/files/5038649/Exploring.the.extent.of.artificial.agricultural.drainage_2019posterv2.pdf)
**FW: RACT for SSWR2 Aquatic Mapping - updates**

**Comment by debboutr** [comment]
```
WsPctFull {'max': 100.00000000000007, 'min': 0.0}
PctAgDrainageCat {'max': 100.00000000000004, 'min': 0.0}
PctAgDrainageWs {'max': 100.00000000000004, 'min': 0.0}
PctNo_AgDrainageCat {'max': 100.00000000000007, 'min': 0.0}
CatAreaSqKm {'max': 65014.443, 'min': 0.0009}
WsAreaSqKm {'max': 3133391.2218000013, 'min': 0.0009}
PctNo_AgDrainageWs {'max': 100.00000000000007, 'min': 0.0}
CatPctFull {'max': 100.0, 'min': 0.0}
COMID {'max': 948100740, 'min': -504212}
```
