### ISSUE TITLE
Anamoly in data file

### ISSUE THREAD

**Issue by bidhya** [USEPA/StreamCat#3]
I am referring to specific file:
../StreamCat/HydroRegions/NLCD2011_Region10L.csv; Row 131609 (having COMID field 24668374)

This row has around 50 columns, instead of usual 37 for other rows. I am not quite sure what this extra columns signify. Can you please verify what is going on here.

**Comment by mhweber** [comment]
@bidhya  - I don't see this either opening the .csv file in excel or in R:
test = read.csv('NLCD2011_Region10L.csv')
names(test)
test_row = test[test$COMID==24668374,]

Can you try downloading again and check?  I do see we recycled names from NLCD2006 so I'll be updating the files with 'NLCD2011' in the field names shortly.

**Comment by bidhya** [comment]
Thank you @mhweber The issue with data anomaly I mention here seems fixed in the new file (looks like they were updated today). I can send you the old file if you want to study the problem (I downloaded them about a week ago).

**Comment by mhweber** [comment]
Thanks @bidhya - we have the old versions as well.  The problem you mention had occurred in the past where part of our processing did not correctly force a new line - we've since built in methods to prevent that happening.
