### ISSUE TITLE
IOOS channel no longer contains the required packages

### ISSUE THREAD

**Issue by mmfink** [USEPA/StreamCat#4]
I haven't checked every package, but **expat** and **rasterio** are now more recent versions, and **snuggs** is missing on https://anaconda.org/ioos.  I haven't been able to find the exact versions required elsewhere on Anaconda for win64.

**Comment by mhweber** [comment]
@mmfink - thanks for note, will update package info shortly

**Comment by mhweber** [comment]
@mmfink - see our updated environment for StreamCat, should address issues, and no longer need ioos channel

**Comment by mmfink** [comment]
Thank you!
