### ISSUE TITLE
NLCD Impervious raster statistics -- NODATAVALUE

### ISSUE THREAD

**Issue by debboutr** [USEPA/StreamCat#94]
### gdal_translate oversight

> After running through all of the new impervious rasters delivered in the 2019 NLCD I have found that the minimum Cat or Ws value for this Continuous metric is `1.0` and not `0.0`. There are a lot of catchments that have NoData w/in them. It is an 8-bit unsigned raster. Looking at the initial `.img` raster downloaded from the NLCD and running `gdalinfo` I noticed that there is NOT a NODATAVALUE set on the raster. However, when using `gdal_translate` to project the `.img` file to `EPSG:5070` and format it as a `GTiff` I had overlooked setting the NODATAVALUE to 0.

#### original use of `gdal_translate`

```
 gdal_translate -a_srs "+proj=aea +lat_1=29.5. {...} +no_defs" \$
      a_nodata 0.0 -co "COMPRESS=LZW" -co "PREDICTOR=2" -co "ZLEVEL=9" \$
      nlcd_2016_impervious_l48_20210604.img \$
      junk_16_cores.tif$
```

#### needed use of `gdal_translate`

```
 gdal_translate -a_srs "+proj=aea +lat_1=29.5. {...} +no_defs" \$
      -of GTiff -co "NUM_THREADS=16" -co "COMPRESS=LZW" -co "PREDICTOR=2" -co "ZLEVEL=9" \$
      nlcd_2016_impervious_l48_20210604.img \$
      junk_16_cores.tif$
```
### What happens when we assign NODATAVALUE to 0
![impervious issue](https://user-images.githubusercontent.com/7052993/129608622-c40b170a-4a1a-4cda-8306-a0421e45543c.png)

> The grey cells in the upper-left of the image are all value 1 in the impervious raster and the rest in the catchment are set to nodata. There are 4 cells of value 1 w/in this catchment. When running stats we get a Count value of 4 as well as a Sum value of 4, so in the end the pctImp for this catchment is 1. This number is incorrect because the NODATAVALUE was set at 0 when using the `gdal_translate` tool.

### Further investigation of prior statistics run on NLCD imperviousness may need to be done?

* references for GDAL compression options: [osgeo](https://trac.osgeo.org/gdal/ticket/3414)   ||    [erouault](http://erouault.blogspot.com/2015/06/multi-threaded-geotiff-compression.html)

**Comment by mhweber** [comment]
@debboutr - note that for NLCD 2019 Imperviousness the background value is 127 https://www.mrlc.gov/downloads/sciweb1/shared/mrlc/metadata/nlcd_2019_impervious_l48_20210604.xml
I just looked at .tif files that I'm assuming are based on updated gdal_translate (?) - they still have a max value of 127, but the legal value range is 0-100 and the 127 cells need to be set to nodata - these are primarily well outside of CONUS and won't affect much, but do need to be set to nodata

**Comment by debboutr** [comment]
#96 closes
